config/routes.rb
Rails.application.routes.draw do
  
  #################################################
  #mailbox folder routes
  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  #conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  #################################################

  resources :posts do
  	resources :comments
  end 

  resources :addresses

	match '#' => 'users#profile', :as => :user_root, via: [:get]
  	
  match 'profile', to: 'users#profile', via: [:get]

  get 'search', to: 'posts#search'

  #################################################
	devise_for :users, controllers: { registrations: "registrations" }
	root to: "home#home_page"

	devise_scope :user do
  		get 'log_in', to: 'devise/sessions#new'
	end

	devise_scope :user do
  		get "sign_up" => "devise/registrations#new"
	end

	devise_scope :user do
  		delete 'logout', to: 'devise/sessions#destroy'
	end	
  #################################################

  #DO NOT DEFINE ANY ROUTES AFTER THIS LINE
	
	match '/:id', to: 'users#show#:id', via: [:get] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!

	def new
	end
	
	def create
		recipients = User.where(id: conversation_params[:recipients])
		conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
		flash[:success] = "Your message was successfully sent!"
		redirect_to conversation_path(conversation)
	end

	def show
		@receipts = conversation.receipts_for(current_user)
		#mark as read
		conversation.mark_as_read(current_user)
	end

	def reply
		current_user.reply_to_conversation(conversation, message_params[:body])
		flash[:notice] = "Your reply message was successfully sent!"
		redirect_to conversation_path(conversation)
	end

	def trash
		conversation.move_to_trash(current_user)
		redirect_to mailbox_inbox_path
	end

	def untrash
		conversation.untrash(current_user)
		redirect_to mailbox_inbox_path
	end

	private

	def message_params
		params.require(:message).permit(:body, :subject)
	end

	def conversation_params
		params.require(:conversation).permit(:subject, :body, recipients:[])
	end
	
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="container row">

	<strong><%= conversation.originator.fullname %></strong> <br>
	<small><b>Subject:</b><%= conversation.subject %></small><br>
	<small><b>Date: </b><%= conversation.messages.last.created_at.strftime("%A, %b, %d, %Y at %I:%M%p") %></small>
	<br>
	<div class="field">
	<%= truncate conversation.messages.last.body, length: 145 %>
	</div>
	<br>
	<%= link_to "View More", conversation_path(conversation) %>
</div>
<br>

app/views/conversations/_form.html.erb
<div class="container">

<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
<form>
    <%= f.label :recipients %>
    <%= f.select(:recipients, User.all.collect {|p| [ p.email, p.id ] }, {}, { multiple: true, class: "form-control" }) %>

    <%= f.label :subject %>
    <%= f.text_field :subject, placeholder: "Subject" %>


    <%= f.label :message %>
    <%= f.text_area :body, placeholder: "Type your message here"%>

  <div class="actions">
    <%= f.submit "Send Message"%>
  </div>

</form>

<% end %>

</div>

app/views/conversations/_messages.html.erb
<div class="wrapper">
<% @receipts.each do |receipt| %>
	<% message = receipt.message %>
	<h5><strong><%= message.sender.fullname %></strong> <br>
	<small>
	<b>Subject: </b><%= message.subject %> </small><br>
	
	<small>
	<b>Date:</b>
	<%= message.created_at.strftime("%A, %b %d %Y") %>
	<br>
	<b>Time:</b>
	<%= message.created_at.strftime("%I:%M %p") %>
	</small>
	</h5>

	<h4>
	<%= message.body %>
	</h4>
<% end %>
</div>

app/views/conversations/new.html.erb
<%= render partial: "mailbox/folder_view", locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="container">
<div class="row">
	<div class="spacer"></div>
	<div class="six columns">
		<%= link_to "Compose", new_conversation_path, :class=> "button" %>
		<div class="six columns.u-pull-right">
			<% if conversation.is_trashed?(current_user) %>
				<%= link_to "Untrash", untrash_conversation_path(conversation), method: :post, :class=> "button" %>
			<% else %>
				<%= link_to "Move to trash", trash_conversation_path(conversation), method: :post,
						data: { confirm: "Are you sure?" }, :class=> "button" %>
			<% end %>

		</div>
	</div>


	<div class="eight columns" >
		<%= render partial: "messages" %>
		<!-- Reply Form -->
		<%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
			<div class="field">
				<%= f.text_area :body, placeholder: "Reply Message", rows: 4 %>
			</div>

			<div class="actions">
    			<%= f.submit %>
  			</div>
		<% end %>	
	</div>
</div>
</div>