config/routes.rb
Rails.application.routes.draw do
  
  #################################################
  #mailbox folder routes
  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  #conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  #################################################

  resources :posts do
  	resources :comments
  end 

  resources :addresses

	match '#' => 'users#profile', :as => :user_root, via: [:get]
  	
  match 'profile', to: 'users#profile', via: [:get]

  get 'search', to: 'posts#search'

  #################################################
	devise_for :users, controllers: { registrations: "registrations" }
	root to: "home#home_page"

	devise_scope :user do
  		get 'log_in', to: 'devise/sessions#new'
	end

	devise_scope :user do
  		get "sign_up" => "devise/registrations#new"
	end

	devise_scope :user do
  		delete 'logout', to: 'devise/sessions#destroy'
	end	
  #################################################

  #DO NOT DEFINE ANY ROUTES AFTER THIS LINE
	
	match '/:id', to: 'users#show#:id', via: [:get] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home_page
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home_page.html.erb
<!DOCTYPE HTML>

<html>

	<head>
		<title>UNIRIDE</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
	</head>
	<body>

		<!-- Banner -->
			<section id="banner">


				<% if current_user %>
				<h2><span style="font-weight:bold"><%= first_letter_uppercase current_user.firstName%> <%= current_user.lastName%></span><br> Where do you want to go today?</p>
				<p><%= link_to "Post a Trip", new_post_url, :class=>"button special"%> <%= link_to "Look for a ride", search_path, :class=>"button special"%></p>
				<%end%>

				<%unless user_signed_in? %>
				<h2><span style="font-weight:bold">UNIRIDE</span><br> Share Save Smile</p>

				<ul class="actions">
					<li><%= link_to "Log In", log_in_url, :class=>"button special"%></a></li>
				</ul>
				<ul class="actions">
					<li><%= link_to "Sign Up", sign_up_url, :class=>"button special"%></li>
				</ul>
			</section>

		<!-- One -->
			<section id="one" class="wrapper special">
				<div class="inner">
					<header class="major">
						<h2>Let's Ride with UniRide</h2>
					</header>
					<div class="features">
						<div class="feature">
							<i class="fa fa-university"></i>
							<h3>College Student Driver</h3>
							<p>All driver and passanger are all college student.</p>
						</div>
						<div class="feature">
							<i class="fa fa-users"></i>
							<h3>Meet And Connect</h3>
							<p>By using uniride you have the chance to meet new friends and build up your connection with other college students.</p>
						</div>
						<div class="feature">
							<i class="fa fa-car"></i>
							<h3>Split the Gas</h3>
							<p>When you drive with somebody else, you can save more.</p>
						</div>
						<div class="feature">
							<i class="fa fa-envelope-o"></i>
							<h3>Send Message</h3>
							<p>You can send messages by peer to peer message application via Uniride application.</p>
						</div>
						<div class="feature">
							<i class="fa fa-smile-o"></i>
							<h3>Smile</h3>
							<p>By meet new connections, new friends, and save your pocket more and more, riding with Uniride will always makes you smile.</p>
						</div>
					</div>
				</div>
				<%end%>
			</section>

			<section id="one" class="wrapper special">
					<% if current_user %>
					 <ul class="actions">
						<li><%= link_to "Sign Out", destroy_user_session_path, :method=> :delete, :class=>"button special"%></li>	
					</ul>
					<%end%>
			</section>		


		<!-- Footer -->

			<footer id="footer">
				<div class="copyright">
					&copy; Uniride.2017</a>
				</div>
			</footer>

		<!-- Scripts -->
			<!-- <script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<!-- <script src="assets/js/main.js"></script> -->

	</body>
</html>