config/routes.rb
Rails.application.routes.draw do
  
  #################################################
  #mailbox folder routes
  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  #conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  #################################################

  resources :posts do
  	resources :comments
  end 

  resources :addresses

	match '#' => 'users#profile', :as => :user_root, via: [:get]
  	
  match 'profile', to: 'users#profile', via: [:get]

  get 'search', to: 'posts#search'

  #################################################
	devise_for :users, controllers: { registrations: "registrations" }
	root to: "home#home_page"

	devise_scope :user do
  		get 'log_in', to: 'devise/sessions#new'
	end

	devise_scope :user do
  		get "sign_up" => "devise/registrations#new"
	end

	devise_scope :user do
  		delete 'logout', to: 'devise/sessions#destroy'
	end	
  #################################################

  #DO NOT DEFINE ANY ROUTES AFTER THIS LINE
	
	match '/:id', to: 'users#show#:id', via: [:get] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :addresses, :dependent => :destroy, inverse_of: :post
	has_many :comments
  has_many :custom_points
  after_save :get_midpoints
  

	accepts_nested_attributes_for :addresses, 
	:allow_destroy => true, :reject_if => :all_blank

  def create_point(lat, lon, dis_left, dis_sor)
    CustomPoint.create(latitude: lat, longitude: lon, distance_left: dis_left, distance_source: dis_sor, post_id: self.id)
  end

  def set_iframe_src
    main_string = "https://www.google.com/maps/embed/v1/directions?key=AIzaSyD1zV2b2rTtvUYLSOL9CiNxTKiB2hMBeCI"
    origin_tag = "&origin="
    destination_tag = "&destination="
    origin_coord = ""
    destination_coord = ""
    if self.addresses.count>2
      detours = Array.new
      detour_group = ""
      detour_tag = "&waypoints="
      detour_coord = ""
    end

    self.addresses.each_with_index do |address, index|
      coordinates = address.latitude.to_s + "," + address.longitude.to_s

      if index==0
        origin_coord = address.street.to_s + "+" + address.city.to_s + "+" + address.state.to_s
      end

      if index==1
        destination_coord = address.street.to_s + "+" + address.city.to_s + "+" + address.state.to_s
      end

      if index>1
        detour_coord = address.street.to_s + "+" + address.city.to_s + "+" + address.state.to_s
        detours << detour_coord
      end

    end

    if !detours.nil?
      detours.each_with_index do |detour, index|
        unless index+1==detours.count
          detour_group = detour_group + detour + "|"
        else
          detour_group = detour_group + detour
        end
      end
    detour_tag = detour_tag + detour_group
    end

    origin_tag = origin_tag + origin_coord
    destination_tag = destination_tag + destination_coord
    detour_tag.nil? ? main_string = main_string + origin_tag + destination_tag : main_string = main_string + origin_tag + destination_tag + detour_tag
  end

  def self.search_coordinates(street1, city1, state1, street2, city2, state2)
    street1 = street1.to_s
    city1 = city1.to_s
    state1 = state1.to_s
    zip1 = street2.to_s
    city2 = city2.to_s
    state2 = state2.to_s
      search_results = Array.new
    if (!street1.empty? && !city1.empty? && !state1.empty? && !street2.empty? && !city2.empty?  && !state2.empty?)
      f = street1 + ", " + city1 + ", " + state1
      s = street2 + ", " + city2 + ", " + state2
      from = Geocoder.coordinates(f)
      to = Geocoder.coordinates(s)
      total_dis = 3
      source_matched = false
      destination_matched = false

      Post.all.each do |post|
        points = post.custom_points.order("distance_source")
        points.each do |cp|
          unless (destination_matched)
            if(!source_matched)
              dis1 = Geocoder::Calculations.distance_between([from[0], from[1]], [cp.latitude, cp.longitude])
              if dis1<=3
                source_matched = true
              end
            else
              dis2 = Geocoder::Calculations.distance_between([to[0], to[1]], [cp.latitude, cp.longitude])
              if(dis2<=3)
                destination_matched=  true
                search_results.push(post)
                break
              end
            end
          end
        end
        source_matched = false
        destination_matched = false
      end 
    end
    search_results
  end

  def self.search_string(street1, city1, zip1, street2, city2, zip2)
    street1.to_s.rstrip
    city1.to_s.rstrip
    zip1.to_s.rstrip
    street2.to_s.rstrip
    city2.to_s.rstrip
    zip2.to_s.rstrip
    results ||= Array.new
    Post.all.each do |post|
      results.push(post) if search_through_addresses(post, street1, city1, zip1, street2, city2, zip2)
    end
    results
  end

  def self.search_through_addresses(post, street1, city1, zip1, street2, city2, zip2)
    source_matched = false
    source_matched_index = -1
    destination_matched = false
    destination_matched_index = -1

    post.addresses.each_with_index do |address, index|
      next if index==1
      if check_address(address, street1, city1, zip1)
        source_matched = true
        source_matched_index = index
        break
      end
    end

    if source_matched
      source_matched_index==0 ? addresses_destination=post.addresses[2..post.addresses.count-1] : 
      addresses_destination=post.addresses[source_matched_index..post.addresses.count-1]

      addresses_destination.each_with_index do |address, index|
        if check_address(address, street2, city2, zip2)
          destination_matched = true
          destination_matched_index = index
          break
        end
        if index == addresses_destination.count-1
          if check_address(post.addresses.second, street2, city2, zip2)
            destination_matched = true
            destination_matched_index = 1
            break
          end
        end
      end
    end

    source_matched && destination_matched ? true : false
  end

  def self.check_address(address, street, city, zip)
    check_street(address, street) || 
        check_city(address, city) || 
        check_zip(address, zip)
  end


  def self.check_street(address, street)
    street.nil? || street.empty? ? false : address.street.downcase==street.downcase
  end

  def self.check_city(address, city)
    city.nil? || city.empty? ? false : address.city.downcase==city.downcase  
  end

  def self.check_zip(address, zip)
    zip.nil? || zip.empty? ? false : address.zip==zip
  end

  private def get_midpoints
    if self.custom_points.any?
      CustomPoint.where(:post_id=>self.id).destroy_all
    end
    if self.addresses.count == 2
      get_midpoints2(self.addresses.first, self.addresses.second)
    else
      self.addresses.each_with_index do |address, index|
        next if index==0 || index==1
        get_midpoints2(self.addresses.first, address) if index==2
        get_midpoints2(address, self.addresses.second) if index==self.addresses.count-1

        get_midpoints2(self.addresses[index-1], address) if self.addresses.count!=3
      end
    end
  end

    #code for finding midpoints
  #currently only checks for midpoints between source and destination
  $outArr = Array.new()
  $outArr2 = Array.new()
  $t = true

  private def get_midpoints2(address1, address2)
    lat1 = address1.latitude
    lon1 = address1.longitude

    lat2 = address2.latitude    
    lon2 = address2.longitude

    @limit = 5.0
  
    @dis = self.addresses.first.distance_to(self.addresses.second)

    latLon = CustomPoint.new()
    
    #source
    point1 = create_point(lat1, lon1, 0.0, 0.0)

    $outArr.push(point1)

    #destination
    point2 = create_point(lat2, lon2, 0.0, @dis)

    $outArr.push(point2)
    $outArr2 = $outArr.clone
   
    t1 = $outArr.count

    if @dis >= @limit
      while ($t)
       
        i = 0
        while  (i < t1 - 1)
          print ">Value of t1 is:- #{t1} and i is #{i} \n"
          print ">Distance source at index #{i}: #{$outArr[i].distance_source}\n"
          cal_midpoint($outArr[i].latitude, $outArr[i].longitude,
             $outArr[i+1].latitude, $outArr[i+1].longitude,
              self.addresses.first)
          #$outArr.sort_by {|obj| obj.distance_source}          
          i += 1
        end

        puts $outArr.inspect
        print "---->Value of t1 is:- #{t1} and i is #{i}\n"
        if ($t == false)
          print "****OutLoop will stop now******\n"
        end
        $outArr.clear
        $outArr = $outArr2.clone
        t1 = $outArr.count
      end  
    end

    i = $outArr.count - 1
    dis = Geocoder::Calculations.distance_between([$outArr[i].latitude, $outArr[i].longitude], [$outArr[i - 1].latitude, $outArr[i - 1].longitude])
    $outArr[i].distance_left = dis
    
    $outArr.each_with_index do |cp, index|
      next if index==0
      cp.distance_left = Geocoder::Calculations.distance_between([cp.latitude, cp.longitude], [$outArr[index-1].latitude, $outArr[index-1].longitude])
      cp.save
    end

    $outArr.clear
    $outArr2.clear
    $t = true

  end

  
  #This method calculates and stores the midpoints in the table
  def cal_midpoint(lat1, lon1, lat2, lon2, sou)
    midpoint = Geocoder::Calculations.geographic_center([[lat1, lon1], [lat2, lon2]])
    lat3 = midpoint[0]
    lon3 = midpoint[1]

    #first save the current midpoint
    mid_temp = CustomPoint.new
    mid_temp.latitude = lat3
    mid_temp.longitude = lon3
    mid_temp.distance_source = sou.distance_to([lat3, lon3])
    mid_temp.distance_left = Geocoder::Calculations.distance_between([lat1, lon1], [lat3, lon3])
    mid_temp.post_id = self.id
    $outArr2.push(mid_temp) 
    $outArr2.sort_by! {|obj| obj.distance_source}
    dis = Geocoder::Calculations.distance_between([$outArr2[0].latitude, $outArr2[0].longitude] , [$outArr2[1].latitude, $outArr2[1].longitude])
      
    #create_point(lat3, lon3, 0, distan)  
    if dis <= 5
      $t = false
    end
  end

  private_class_method :search_through_addresses, :check_address, :check_street ,:check_city, :check_zip

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def search
    #@date_test = params.to_unsafe_h.slice(:date)

    @search_results = Post.search_coordinates(params[:street1], params[:city1], params[:state1],
      params[:street2], params[:city2], params[:state2])
  end

  # GET /posts
  # GET /posts.json
  def index
    #visitor_latitude = request.location.latitude
    #visitor_longitude = request.location.longitude
    @visitor_latitude = 37.35138
    @visitor_longitude = -121.850291
    #@posts = Array.new
    @posts = Post.all
    @source_near_me = Array.new()
    get_this_post
    #Post.where(:id => Addresses.full_address.near(visitor_latitude, visitor_longitude).post_id)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @addresses = @post.addresses
    @iframe_src = @post.set_iframe_src
  end

  #
  def get_this_post
   #temp = Address.near([@visitor_latitude, @visitor_longitude], 20)
   #temp = Post.all() 
   t = Post.all()
   limit = 8

   t.each do |temp1|
        dist = temp1.addresses.first().distance_to([@visitor_latitude, @visitor_longitude])
       
        if dist <= limit
          #@posts.push(temp1)
        end
   end

  end

  # GET /posts/new
  def new
    @added=false
    @post = Post.new
    @post.addresses.new
    @post.addresses.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.addresses_count = @post.addresses.count

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post.update_attribute(:addresses_count, @post.addresses.count)
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:addresses_count, :title, :description, :date, 
        addresses_attributes: [:id, :street, :city, :state, :zip, :_destroy])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_address_fields.html.erb
<div class="nested-fields">
  <div class="row">
      <div class="five columns">
        <%= f.label :street %>
        <%= f.text_field :street, :class=>"u-full-width", :required=>true %>
      </div>

      <div class="three columns">
        <%= f.label :city %>
        <%= f.text_field :city, :class=>"u-full-width", :required=>true %>
      </div>

      <div class="two columns">
        <%= f.label :state %>
        <%= f.text_field :state, :class=>"u-full-width", :required=>true %>
      </div>

      <div class="two columns">
        <%= f.label :zip %>
        <%= f.text_field :zip, :value=>"", :class=>"u-full-width" %>
      </div>
  </div>
  <%if !local_assigns[:init_field]%>
    <h6><span style="font-size: 18px"><%= link_to_remove_association('( Remove )', f) %></span></h6>
  <%elsif local_assigns[:editing] && local_assigns[:i]>1 %>
    <h6><span style="font-size: 18px"><%= link_to_remove_association('( Remove )', f) %></span></h6>
  <%end%>
</div>

app/views/posts/_form.html.erb
<%editing = false unless editing%>
<div class="container">
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :required=>true %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description%>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date, :required=>true %>
  </div>

  <%= f.fields_for :addresses do |address| %>
    <% if address.index==0 %>
      <h4>Source</h4>
    <%elsif address.index==1%>
      <h4>Destination</h4>
    <%else%>
      <h4>
      Detour - <%= address.index-1 %>
      </h4>
    <%end%>
    <%= render 'address_fields', f: address, init_field: true, editing: editing, i: address.index %>
  <% end %>
  <h5 class='links'>
    <%= link_to_add_association 'add detour', f, :addresses%>
  </h5>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing Post</h1>

<%= render 'form', post: @post, editing: true %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.date %></td>
        <td><%= post.user.firstName %></td>
        <td><%= post.addresses.count %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/search.html.erb
<%= form_tag search_path, :method => 'get' do %>
	<div class="container">
	<div class="row">
		<div class="one-half column">
		<h3>From</h3>
			<label>Street:</label>
			<%= text_field_tag :street1, (params[:street1] or "")%>
			<div class="row">
				<div class="eight columns">
					<label>City:</label>
					<%= text_field_tag :city1, (params[:city1] or "")%>
				</div>
				<div class="four columns">
					<label>State:</label>
					<%= text_field_tag :state1, (params[:state1] or "")%>
				</div>
			</div>
		</div>
		<div class="one-half column">
		<h3>To</h3>
			<label>Street:</label>
			<%= text_field_tag :street2, (params[:street2] or "")%>
			<div class="row">
				<div class="eight columns">
					<label>City:</label>
					<%= text_field_tag :city2, (params[:city2] or "")%>
				</div>
				<div class="four columns">
					<label>State:</label>
					<%= text_field_tag :state2, (params[:state2] or "")%>
				</div>
			</div>
		</div>
		<%= submit_tag "Search", :name=>nil, :class=>"u-full-width" %>
	</div>
	</div>
<% end %>

<div class="container">
	<%if @search_results.any?%>
		<% @search_results.each do |result| %>
			<%= link_to "#{result.title}", result %></br>
		<% end %>
	<%else%>
		<center><h6> Nothing to Show Here </h6>
	<%end%>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
 
<div class="container" >
  <h2><%= @post.title %></h2>
  <p>Posted by <%= @post.user.firstName %> <%= @post.user.lastName %> <%= time_ago_in_words(@post.created_at) %> ago</p>

  <p><%= @post.description %></p>

  <p>
    <strong>Address:</strong>
    <% @addresses.each_with_index do |address, index| %>

    	<% if index==0 %>
        <h4>Source</h4>
      <%elsif index==1%>
      	<h4>Destination</h4>
      <%else%>
        <h4>Detour <%= index-1 %></h4>
      <%end%>

  	<p><%= address.full_address %>	
  	<br/>Latitude: <%= address.latitude %>
  	<br/>Longitude: <%= address.longitude %>
  	</p>
    <%end%>
  </p>

  <iframe
    width="600"
    height="450"
    frameborder="0" style="border:0"
    src="<%=@iframe_src%>" allowfullscreen>
  </iframe>

  <h3>Comments: </h3>
  <%= render @post.comments %>

  <h3>Reply to Post: </h3>
  <%= render 'comments/form' %>


  <% if user_signed_in? %>
    <% if @post.user_id == current_user.id %>
      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Back', posts_path %>
    <% end %>
  <% end %>

</div>