config/routes.rb
Rails.application.routes.draw do
  
  #################################################
  #mailbox folder routes
  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  #conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  #################################################

  resources :posts do
  	resources :comments
  end 

  resources :addresses

	match '#' => 'users#profile', :as => :user_root, via: [:get]
  	
  match 'profile', to: 'users#profile', via: [:get]

  get 'search', to: 'posts#search'

  #################################################
	devise_for :users, controllers: { registrations: "registrations" }
	root to: "home#home_page"

	devise_scope :user do
  		get 'log_in', to: 'devise/sessions#new'
	end

	devise_scope :user do
  		get "sign_up" => "devise/registrations#new"
	end

	devise_scope :user do
  		delete 'logout', to: 'devise/sessions#destroy'
	end	
  #################################################

  #DO NOT DEFINE ANY ROUTES AFTER THIS LINE
	
	match '/:id', to: 'users#show#:id', via: [:get] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uniride</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Raleway:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
  </head>

  <body class="special">
  <%if user_signed_in? %>
  <div class="container-nav">
      <div class="row">
        <div class="four columns">
          <%=link_to 'UniRide', root_url, :class=>"uniride-nav u-pull-left" %></div>
        <div class="two columns">
          <span class="nav-element">
            <%= link_to'Feed', posts_url, :class => "nav-element" %>
          </span>
        </div>
        <div class="two columns">
          <%= link_to'Profile', profile_url, :class => "nav-element" %>
        </div>
        <div class="two columns">
          <%= link_to 'Inbox', mailbox_inbox_path, :class=>"nav-element" %>
        </div>
        <div class="two columns">
          <%= link_to'Search', search_path, :class => "nav-element" %>
        </div>
      </div>
  </div>

  <div class="create-margin"></div>
  <%end%>
  <% unless user_signed_in?%> 
  	<div class="alert-notice"><p class="notice"><%= notice %></p></div>
  <% end %>
  	<div class="alert-error"><p class="alert">
      <% if alert %>
        <button class="close"> × </button>
        <%= alert %>
      <script>      
        $(".close").click(function(){
          $(".alert-error").hide();
        });
      </script>
      <% end %>
    </p></div>

    <%= yield %>
  </body>
</html>